spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gymhelper?createDatabaseIfNotExist=true&serverTimezone=UTC
        driverClassName: com.mysql.cj.jdbc.Driver
        username: sa
        password: password
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
